# Generated by Django 5.2.6 on 2025-11-11 05:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_remove_producto_fecha_vencimiento_and_more'),
        ('venta_transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'ordering': ['-fecha_actualizacion'], 'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
        migrations.AlterModelOptions(
            name='detallecarrito',
            options={'ordering': ['-fecha_agregada'], 'verbose_name': 'Detalle de Carrito', 'verbose_name_plural': 'Detalles de Carritos'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha_venta'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='total',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='stripe_client_secret',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total_venta',
        ),
        migrations.AddField(
            model_name='carrito',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Abandonado', 'Abandonado'), ('Convertido', 'Convertido')], default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carrito',
            name='origen',
            field=models.CharField(default='FlutterApp', max_length=50),
        ),
        migrations.AddField(
            model_name='detallecarrito',
            name='fecha_agregada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pago',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogo.cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_entrada',
            field=models.CharField(choices=[('Web', 'Web'), ('Móvil', 'Móvil'), ('Teléfono', 'Teléfono'), ('Mostrador', 'Mostrador')], default='Móvil', max_length=50),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('Contado', 'Contado')], default='Contado', max_length=50),
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='catalogo.cliente'),
        ),
        migrations.AlterField(
            model_name='detallecarrito',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='detallecarrito',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='venta_transacciones.carrito'),
        ),
        migrations.AlterField(
            model_name='detallecarrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='detallecarrito',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesando', 'Procesando'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Reembolsado', 'Reembolsado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('efectivo', 'Efectivo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pago',
            name='venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='venta_transacciones.venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
