# Generated by Django 5.2.6 on 2025-11-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta_transacciones', '0002_alter_carrito_options_alter_detallecarrito_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='stripe_client_secret',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
