# Generated by Django 5.2.6 on 2025-11-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta_transacciones', '0002_venta_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='total_venta',
            new_name='total',
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_entrada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
