# Generated by Django 5.2.6 on 2025-11-11 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta_transacciones', '0003_rename_total_venta_venta_total_venta_metodo_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
