# Generated by Django 5.2.6 on 2025-11-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso_seguridad', '0003_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='link_accion',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de Acción'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='prioridad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='aviso',
            name='tipo',
            field=models.CharField(blank=True, default='Informativo', max_length=50),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='asunto',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje'),
        ),
    ]
