# Generated by Django 5.2.6 on 2025-11-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso_seguridad', '0004_aviso_imagen_url_aviso_link_accion_aviso_prioridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Programado', 'Programado'), ('Enviado', 'Enviado'), ('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='Activo', max_length=20),
        ),
    ]
