# Generated by Django 5.2.6 on 2025-10-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_vencimiento',
        ),
        migrations.AddField(
            model_name='producto',
            name='ano_garantia',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
