# Generated by Django 5.2.6 on 2025-11-10 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_producto_codigo_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='preferencia_compra',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='total_compras',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_medida',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
