# Generated by Django 5.2.6 on 2025-11-11 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_inventarioproducto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_medida',
        ),
    ]
