# Generated by Django 5.2.6 on 2025-11-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_alter_cliente_usuario'),
        ('catalogo', '0008_remove_producto_fecha_vencimiento_and_more'),
    ]

    operations = [
    ]
