# Generated by Django 5.2.6 on 2025-10-25 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prediccion', models.DateField()),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('venta_predicha', models.IntegerField()),
                ('confianza', models.FloatField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.categoria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Predicción de Ventas',
                'verbose_name_plural': 'Predicciones de Ventas',
                'db_table': 'prediccion_ventas',
                'ordering': ['-fecha_prediccion'],
            },
        ),
    ]
