# Generated by Django 5.2.6 on 2025-11-11 21:31

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_inteligencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prediccionventas',
            options={'ordering': ['-fecha_prediccion', 'categoria', 'periodo_inicio'], 'verbose_name': 'Predicción de Venta', 'verbose_name_plural': 'Predicciones de Ventas'},
        ),
        migrations.RemoveField(
            model_name='prediccionventas',
            name='producto',
        ),
        migrations.AlterField(
            model_name='prediccionventas',
            name='confianza',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='prediccionventas',
            name='fecha_prediccion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prediccionventas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prediccionventas',
            name='venta_predicha',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterModelTable(
            name='prediccionventas',
            table=None,
        ),
    ]
